# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 09:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '会议内容',
                'verbose_name_plural': '会议内容',
            },
        ),
        migrations.CreateModel(
            name='Meetmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('pnum', models.IntegerField()),
                ('livable', models.CharField(max_length=100)),
                ('indate', models.DateField(blank=True, null=True)),
                ('outdate', models.DateField(blank=True, null=True)),
                ('invoice', models.BooleanField()),
            ],
        ),
    ]
